# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 14:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagename', models.CharField(max_length=200)),
                ('eyes', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='/diabetics/%Y/%M/%D')),
            ],
        ),
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodr', models.DecimalField(decimal_places=15, max_digits=20)),
                ('mild', models.DecimalField(decimal_places=15, max_digits=20)),
                ('moderate', models.DecimalField(decimal_places=15, max_digits=20)),
                ('severe', models.DecimalField(decimal_places=15, max_digits=20)),
                ('proliferative', models.DecimalField(decimal_places=15, max_digits=20)),
                ('imagename', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diabetics.ImageName')),
            ],
        ),
    ]
