# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 06:13
from __future__ import unicode_literals

import diabetics.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diabetics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='severity',
            name='result',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='imagename',
            name='image',
            field=models.ImageField(null=True, upload_to=diabetics.models.ImageName.get_image_path),
        ),
    ]
